- alias: Miflora Restart on Rpis
  id: miflora_restart_on_rpis
  trigger:
  - event: start
    platform: homeassistant
  action:
  - entity_id: script.miflora_restart_rpis
    service: script.turn_on
- id: '1580749955335'
  alias: Plant Sensor Notification
  description: ''
  trigger:
  - below: '20'
    entity_id: sensor.loft_ficus_moisture
    platform: numeric_state
  - below: '15'
    entity_id: sensor.master_zzplant_mqtt2_moisture
    platform: numeric_state
  - below: '15'
    entity_id: sensor.guest_dracaena_mqtt1_moisture
    platform: numeric_state
  - below: '15'
    entity_id: sensor.front_zzplant_moisture
    platform: numeric_state
  - below: '15'
    entity_id: sensor.living_zzplant_mqtt2_moisture
    platform: numeric_state
  - below: '15'
    entity_id: sensor.living_dracaena_mqtt2_moisture
    platform: numeric_state
  - below: '7'
    entity_id: sensor.landing_snake_left_mqtt2_moisture
    platform: numeric_state
  - below: '7'
    entity_id: sensor.landing_snake_right_mqtt2_moisture
    platform: numeric_state
  condition: []
  action:
  - service: notify.telegram
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} is at ({{ trigger.to_state.state }})."
  - service: input_boolean.turn_on
    entity_id: input_boolean.plants_warning
- id: '1580749955335_off'
  alias: Plant Sensor Warning Off
  description: ''
  trigger:
  - above: '19'
    entity_id: sensor.loft_ficus_moisture
    platform: numeric_state
  - above: '14'
    entity_id: sensor.master_zzplant_mqtt2_moisture
    platform: numeric_state
  - above: '14'
    entity_id: sensor.guest_dracaena_mqtt1_moisture
    platform: numeric_state
  - above: '14'
    entity_id: sensor.front_zzplant_moisture
    platform: numeric_state
  - above: '14'
    entity_id: sensor.living_zzplant_mqtt2_moisture
    platform: numeric_state
  - above: '14'
    entity_id: sensor.living_dracaena_mqtt2_moisture
    platform: numeric_state
  - above: '6'
    entity_id: sensor.landing_snake_left_mqtt2_moisture
    platform: numeric_state
  - above: '6'
    entity_id: sensor.landing_snake_right_mqtt2_moisture
    platform: numeric_state
  condition: []
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.plants_warning
- id: '1584811198700'
  alias: Seedlings Heat Every 20 Min
  description: ''
  trigger:
  - minutes: '/15'
    platform: time_pattern
  condition: []
  action:
  - entity_id: switch.dome_onoff_plugin_switch_switch
    service: switch.toggle
#  - data:
#      message: Seedling heat is {{ states.switch.dome_onoff_plugin_switch_switch.state }}.
#    service: notify.telegram
